[package]
name = "onebitml"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
pyo3 = { version = "0.27.1", features = ["extension-module"] }
nalgebra = { version = "0.34.1", features = ["rand"] }
num-traits = "0.2.19"
