[project]
name = "one_bit_ml_models"
version = "0.1.0"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.maturin]
python-source = "python/src"
generate-version-file = false